substitutions:
  _DEPLOY_REGION: northamerica-south1
  _AR_HOSTNAME: northamerica-south1-docker.pkg.dev
  _AR_REPOSITORY: irflies-backend
  _SERVICE_NAME: irflies-api
  _IMAGE_NAME: irflies-api
  _RUN_SA: irflies-api-sa@irflies-uv.iam.gserviceaccount.com
  _YOLO_MODEL_URI: gs://irflies-uv-models/yolo/eyes_yolo_uno_dos_ojos_v1.pt
  _CLASSIFIER_MODEL_URI: gs://irflies-uv-models/classification/irflies_classifier_uno_dos_ojos_v1.h5
  _CLASSIFIER_LABELS_CSV: ef8,ef9

steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_AR_HOSTNAME}/${PROJECT_ID}/${_AR_REPOSITORY}/${_IMAGE_NAME}:${SHORT_SHA}",
        "-f",
        "backend/Dockerfile",
        "backend"
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "${_AR_HOSTNAME}/${PROJECT_ID}/${_AR_REPOSITORY}/${_IMAGE_NAME}:${SHORT_SHA}"
      ]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run", "deploy", "${_SERVICE_NAME}",
        "--image", "${_AR_HOSTNAME}/${PROJECT_ID}/${_AR_REPOSITORY}/${_IMAGE_NAME}:${SHORT_SHA}",
        "--region", "${_DEPLOY_REGION}",
        "--platform", "managed",
        "--allow-unauthenticated",
        "--no-traffic",
        "--tag", "candidate",
        "--service-account", "${_RUN_SA}",
        "--max-instances", "8",
        "--max", "8",
        "--concurrency", "1",
        "--cpu", "1",
        "--memory", "4Gi",
        "--timeout", "900",
        "--set-env-vars",
        "^@^IRFLIES_MODELS_BUCKET=irflies-uv-models@IRFLIES_TMP_BUCKET=irflies-uv-tmp@IRFLIES_MAX_UPLOAD_MB=10@IRFLIES_SIGNED_URL_TTL_SECONDS=900@IRFLIES_DEFAULT_DETECTION_CONF=0.25@IRFLIES_YOLO_ENABLED=true@IRFLIES_YOLO_MODEL_URI=${_YOLO_MODEL_URI}@IRFLIES_YOLO_MAX_DETECTIONS=10@IRFLIES_YOLO_IOU_THRESH=0.6@IRFLIES_CLASSIFIER_ENABLED=true@IRFLIES_CLASSIFIER_MODEL_URI=${_CLASSIFIER_MODEL_URI}@IRFLIES_CLASSIFIER_LABELS_CSV=${_CLASSIFIER_LABELS_CSV}@IRFLIES_CLASSIFIER_PREPROCESS=efficientnetv2@IRFLIES_CLASSIFIER_OUTPUT_MODE=auto"
      ]

images:
  - "${_AR_HOSTNAME}/${PROJECT_ID}/${_AR_REPOSITORY}/${_IMAGE_NAME}:${SHORT_SHA}"

options:
  logging: CLOUD_LOGGING_ONLY
