substitutions:
  _DEPLOY_REGION: northamerica-south1
  _AR_HOSTNAME: northamerica-south1-docker.pkg.dev
  _AR_REPOSITORY: irflies
  _SERVICE_NAME: irflies-api
  _IMAGE_NAME: irflies-api
  _RUN_SA: irflies-api-sa@irflies-uv.iam.gserviceaccount.com

steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_AR_HOSTNAME}/${PROJECT_ID}/${_AR_REPOSITORY}/${_IMAGE_NAME}:${SHORT_SHA}",
        "-f",
        "backend/Dockerfile",
        "backend"
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "${_AR_HOSTNAME}/${PROJECT_ID}/${_AR_REPOSITORY}/${_IMAGE_NAME}:${SHORT_SHA}"
      ]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run", "deploy", "${_SERVICE_NAME}",
        "--image", "${_AR_HOSTNAME}/${PROJECT_ID}/${_AR_REPOSITORY}/${_IMAGE_NAME}:${SHORT_SHA}",
        "--region", "${_DEPLOY_REGION}",
        "--platform", "managed",
        "--allow-unauthenticated",
        "--service-account", "${_RUN_SA}",
        "--max-instances", "15",
        "--concurrency", "4",
        "--cpu", "1",
        "--memory", "2Gi",
        "--set-env-vars",
        "^@^IRFLIES_MODELS_BUCKET=irflies-uv-models@IRFLIES_TMP_BUCKET=irflies-uv-tmp@IRFLIES_MAX_UPLOAD_MB=10@IRFLIES_SIGNED_URL_TTL_SECONDS=900@IRFLIES_YOLO_ENABLED=false@IRFLIES_CLASSIFIER_ENABLED=true@IRFLIES_CLASSIFIER_MODEL_URI=gs://irflies-uv-models/classification/refit_model_fixed.h5@IRFLIES_CLASSIFIER_LABELS_CSV=ef8,ef9"
      ]

images:
  - "${_AR_HOSTNAME}/${PROJECT_ID}/${_AR_REPOSITORY}/${_IMAGE_NAME}:${SHORT_SHA}"

options:
  logging: CLOUD_LOGGING_ONLY
