steps:
  # Build
  - name: "gcr.io/cloud-builders/docker"
    dir: "backend"
    args:
      - "build"
      - "-t"
      - "${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}"
      - "."

  # Push
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}"

  # Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "${_SERVICE_NAME}"
      - "--image"
      - "${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}"
      - "--region"
      - "${_DEPLOY_REGION}"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"

images:
  - "${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}"

# <-- ESTO ARREGLA TU ERROR ACTUAL (logs) -->
options:
  logging: CLOUD_LOGGING_ONLY
